<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import ttLogo from '$lib/images/tt-logo-blank.png';

	let y: number;
	let innerHeight: number;

	let loaded = false;
	onMount(() => {
		loaded = true;
	});

	let parallaxY: number;
	$: parallaxY = loaded ? y / (document.documentElement.scrollHeight - innerHeight) : 0;
</script>

<svelte:window bind:scrollY={y} bind:innerHeight />

<svelte:head>
	<title>Seattle Transit Trek: Error {$page.status}</title>
</svelte:head>

<div id="bgImg" style="background-position: 50% {parallaxY * 100}%"></div>

<div class="topLogo"><img src={ttLogo} alt="" /> Seattle Transit Trek</div>

<div class="textWrap">
	<div class="textBlurWrap">
		<svg aria-hidden="true">
			<clipPath id="clipPath">
				<text dominant-baseline="hanging" text-anchor="middle" x="50%" y="0%"></text>
				<text dominant-baseline="hanging" text-anchor="middle" x="50%" y="30%">{$page.status}</text>
			</clipPath>
		</svg>
	</div>
	<div class="textShadowWrap">
		<h1><br /><span>{$page.status}</span></h1>
		<svg aria-hidden="true">
			<mask id="maskPath">
				<rect width="100%" height="100%" fill="white" />
				<text color="black" dominant-baseline="hanging" text-anchor="middle" x="50%" y="0%"></text>
				<text color="black" dominant-baseline="hanging" text-anchor="middle" x="50%" y="30%"
					>{$page.status}</text
				>
			</mask>
		</svg>
	</div>
</div>

<p class="date">{$page?.error?.message ?? 'Something bad happened :('}</p>

<main>
	<p style="text-align: center;">
		{#if $page.status === 404}
			Like Arjun's faith in this site getting built, this page does not exist.
		{:else}
			Something went wrong. Please let Game Control know.
		{/if}
	</p>

	<p class="signupwrap" style="text-align: center; margin-top: 50px; margin-bottom: 0;">
		<a href="/">Back Home</a>
	</p>
</main>

<p class="credit">
	<small
		>This page includes graphical elements <a href="http://www.freepik.com"
			>designed by Rwdd_studios / Freepik</a
		>
		and <a href="http://www.freepik.com">designed by Freepik</a>. This page also includes elements
		that are AI generated by Microsoft Designer.</small
	>
</p>

<style>
	:global(body) {
		padding: 0;
		margin: 0;
	}

	main {
		background: rgba(0, 0, 0, 0.75);
		backdrop-filter: blur(10px);
		box-shadow: 0 0 15px 10px black;

		width: 90%;
		max-width: 1500px;
		margin: 15vh auto 50px auto;
		color: white;
		padding: 5vh 10vh;
		box-sizing: border-box;
		font-family: 'Noto Sans', 'Helvetica', sans-serif;
		font-size: 20px;
	}

	.topLogo {
		position: absolute;
		display: flex;
		flex-direction: row;
		align-items: center;
		justify-content: center;

		color: rgba(255, 255, 255, 0.7);
		font-weight: 900;
		font-size: 50px;
		text-shadow: 5px 5px 10px rgba(0, 0, 0, 0.7);
		-webkit-text-stroke: 2px black;
		paint-order: stroke fill;

		top: 5vh;
		left: 0;
		right: 0;
	}

	.topLogo img {
		width: 100px;
		margin-right: 20px;
		opacity: 0.9;
		box-shadow: 10px 10px 5px 0 rgba(0, 0, 0, 0.5);
	}

	.date {
		color: white;
		font-weight: 900;
		font-size: 50px;
		text-shadow: 5px 5px 10px rgba(0, 0, 0, 0.7);
		-webkit-text-stroke: 2px black;
		paint-order: stroke fill;
		text-align: center;
	}

	.credit {
		padding: 20px 50px;
		color: white;
		max-width: 650px;

		text-shadow: black 0 0 5px;
	}

	.credit a:hover {
		text-decoration: none;
	}

	.credit a,
	.credit a:active {
		color: white;
		text-decoration: underline;
	}

	.textWrap {
		margin-top: max(calc(50vh - 25vw), 100px);
		height: 25vw;
		width: 100%;
		position: relative;

		transform: translateZ(0);
	}

	.textBlurWrap text:nth-child(2),
	.textShadowWrap svg text:nth-child(3),
	.textShadowWrap h1 span {
		font-size: 17.5vw;
	}

	.textShadowWrap {
		margin: 0;
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;

		mask: url(#maskPath);
	}

	.textShadowWrap h1 {
		font-family: 'Noto Sans', 'Helvetica', sans-serif;
		font-weight: 900;
		font-size: 10vw;
		text-align: center;
		margin: 0;
		line-height: 9vw;
		transform: translateY(0.1vw);

		color: white;

		text-shadow: black 0 0 1.5vw;
		-webkit-text-stroke: 1.3vw black;
		paint-order: stroke fill;
	}

	.textShadowWrap svg {
		pointer-events: none;
		font-family: 'Noto Sans', 'Helvetica', sans-serif;
		font-weight: 900;
		font-size: 10vw;
		text-align: center;
		position: absolute;
		top: 0;
		width: 100%;
		height: 25vw;
	}

	#maskPath {
		background: white;
		color: black;
	}

	.textShadowWrap h1 span {
		line-height: 13vw;
		-webkit-text-stroke: 1.8vw black;
	}

	.textBlurWrap {
		pointer-events: none;

		backdrop-filter: invert(1) blur(5px);
		clip-path: url(#clipPath);

		margin: 0;

		font-family: 'Noto Sans', 'Helvetica', sans-serif;
		font-weight: 900;
		font-size: 10vw;
		text-align: center;

		position: absolute;
		top: 0;
		left: 0;
		right: 0;
	}

	.textBlurWrap svg {
		width: 100%;
		height: 25vw;
	}

	#bgImg {
		width: 100%;
		height: 100%;
		position: fixed;
		z-index: -1;
		top: 0;
		left: 0;
		background-image: url($lib/images/transit-trek-bg-wide.png);
		background-size: cover;
		background-position: center;
	}

	@media (max-width: 1100px) {
		main {
			margin-top: 5vh;
			padding: 10px 25px;
		}

		.date {
			margin: 0;
			transform: translateY(-5vh);
		}

		.textWrap {
			margin-top: max(calc(40vh - 25vw), 100px);
			height: 40vw;
		}

		.textBlurWrap svg,
		.textShadowWrap svg {
			height: 50vw;
		}

		.textBlurWrap text:nth-child(2),
		.textShadowWrap svg text:nth-child(3),
		.textShadowWrap h1 span {
			font-size: 26.25vw;
		}

		.textShadowWrap h1 {
			line-height: 13.5vw;
			transform: translateY(0.2vw);

			text-shadow: black 0 0 1.5vw;
			-webkit-text-stroke: 1.6vw black;
		}

		.textBlurWrap text:nth-child(2),
		.textShadowWrap svg text:nth-child(3) {
			transform: translateY(-3.85vw);
		}

		.textShadowWrap svg,
		.textBlurWrap,
		.textShadowWrap h1 {
			font-size: 15vw;
		}

		.textShadowWrap h1 span {
			line-height: 19.5vw;
			-webkit-text-stroke: 2.5vw black;
		}
	}

	@media (max-width: 1000px) {
		.topLogo,
		.date {
			font-size: 5vw;
			-webkit-text-stroke: 0.2vw black;
		}

		.topLogo img {
			width: 10vw;
			margin-right: 2vw;
		}
	}

	@media (max-width: 700px) {
		main {
			margin-top: 10vh;
		}
	}

	@media (min-aspect-ratio: 25/9) {
		.textWrap {
			margin-top: max(5vw, 150px);
		}
	}

	/* .signupwrap {
		margin: 5vw auto;
		padding: 40px 80px;
		text-align: center;

		background: rgba(0, 0, 0, 0.75);
		backdrop-filter: blur(10px);
		box-shadow: 0 0 15px 10px black;

		max-width: 800px;
		box-sizing: border-box;

		display: flex;
		flex-direction: row;
		align-items: center;
		justify-content: center;
	} */

	.signupwrap a {
		padding: 20px 60px;
		display: inline-block;
		color: white;
		text-decoration: none;
		position: relative;
		overflow: hidden;
		text-shadow: 0 0 15px black;
		-webkit-text-stroke: 2px black;
		paint-order: stroke fill;
		font-weight: bold;
		font-size: 25px;
		box-shadow: 0 0 1px 1px white;

		transition: box-shadow 0.5s ease-in-out;
	}

	.signupwrap a:hover,
	.signupwrap a:focus {
		box-shadow: 0 0 20px 0px white;
	}

	.signupwrap a:active {
		transition: box-shadow 0.1s ease-in-out;
		box-shadow: 0 0 20px 0px black;
	}

	.signupwrap a::after {
		content: '➤';
		margin-left: 1em;
		display: inline-block;
		transform: translateX(0);
		transition: transform 0.25s ease-in-out;
	}

	.signupwrap a:hover::after,
	.signupwrap a:focus::after {
		transform: translateX(1em);
	}

	.signupwrap a::before {
		content: '';
		display: block;
		position: absolute;
		z-index: -1;
		background: linear-gradient(
			to right,
			#e6400e 0%,
			#9366b3 25%,
			#0596cf 50%,
			rgba(0, 0, 255, 0) 100%
		);
		top: 0;
		left: 0;
		width: 200%;
		height: 100%;
		transform: translateX(-100%);
		transition: transform 0.5s ease-in-out;
	}

	.signupwrap a:hover::before,
	.signupwrap a:focus::before {
		transform: translateX(0);
	}

	@media (max-width: 800px) {
		.signupwrap {
			flex-direction: column;
			margin-top: 75px;
			margin-bottom: 100px;
		}

		.signupwrap a {
			font-size: 4vw;
		}
	}
</style>
